apiVersion: batch/v1
kind: Job
metadata:
  name: copy-content-job
spec:
  template:
    spec:
      containers:
        - name: copy
          image: busybox
          command: ['sh', '-c', 'echo "Hello from Kubernetes!" > /mnt/data/index.html']
          volumeMounts:
            - name: web-content
              mountPath: /mnt/data
      restartPolicy: Never
      volumes:
        - name: web-content
          persistentVolumeClaim:
            claimName: lsc-lab5-pvc
  backoffLimit: 4
